// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzCT1V8LFulwJqc2S2Y-Wih29JSDj1WHQ',
    appId: '1:1024808321845:web:a85f84a3a1fbcdb1d9427c',
    messagingSenderId: '1024808321845',
    projectId: 'infosec-571a3',
    authDomain: 'infosec-571a3.firebaseapp.com',
    storageBucket: 'infosec-571a3.appspot.com',
    measurementId: 'G-W4XYTFZNEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGzg89gMjmAWtwQkLbpc2VjKE9PiKsiy4',
    appId: '1:1024808321845:android:ec69715f9d222f1ad9427c',
    messagingSenderId: '1024808321845',
    projectId: 'infosec-571a3',
    storageBucket: 'infosec-571a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJbFV5oeJA5E9hnMxh1y4_oSbyim1V5I4',
    appId: '1:1024808321845:ios:7951ba7445d8718bd9427c',
    messagingSenderId: '1024808321845',
    projectId: 'infosec-571a3',
    storageBucket: 'infosec-571a3.appspot.com',
    iosBundleId: 'com.example.passMana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJbFV5oeJA5E9hnMxh1y4_oSbyim1V5I4',
    appId: '1:1024808321845:ios:7951ba7445d8718bd9427c',
    messagingSenderId: '1024808321845',
    projectId: 'infosec-571a3',
    storageBucket: 'infosec-571a3.appspot.com',
    iosBundleId: 'com.example.passMana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzCT1V8LFulwJqc2S2Y-Wih29JSDj1WHQ',
    appId: '1:1024808321845:web:4e6cbf6cfc5d0a9fd9427c',
    messagingSenderId: '1024808321845',
    projectId: 'infosec-571a3',
    authDomain: 'infosec-571a3.firebaseapp.com',
    storageBucket: 'infosec-571a3.appspot.com',
    measurementId: 'G-KQ88B4L76D',
  );

}